<a href="https://colab.research.google.com/github/yusica09/seoul-AI-hub-study/blob/main/3%EC%A3%BC%EC%B0%A8/10_Advanced_RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
tf.__version__

'2.15.0'

In [2]:
layers = tf.keras.layers

### RNN 테스트를 위한 더미데이터 생성

In [3]:
inputs = tf.random.normal([2, 5, 4])

In [4]:
inputs

<tf.Tensor: shape=(2, 5, 4), dtype=float32, numpy=
array([[[-0.24538273, -0.01497399, -0.17145683,  1.3977969 ],
        [-1.5405202 , -1.3604292 , -0.11382049, -0.04012011],
        [-0.3070257 , -1.2349538 ,  2.2304971 ,  0.8341074 ],
        [-0.08772027,  0.49865624,  0.28437397,  0.46033856],
        [ 0.42408118, -0.8600902 ,  1.236416  ,  0.8156111 ]],

       [[-0.18999712, -1.3815571 , -0.33136007, -0.1632942 ],
        [-1.0750673 , -2.5784533 , -0.71872115, -0.51347554],
        [ 0.06528535, -0.11180785,  0.84131956,  1.0187334 ],
        [ 0.6015381 , -1.0673988 , -0.6291547 , -0.9794008 ],
        [ 1.0323014 , -0.4284913 , -1.3416685 ,  0.68226373]]],
      dtype=float32)>

* tf.keras를 이용한 다양한 RNN layer를 구현해보자

## Multi-Layer RNN

![multilayer_rnn](https://user-images.githubusercontent.com/11681225/46912330-5fe5fd00-cfad-11e8-95c2-94bb8e7b1bf6.png)

In [5]:
model = tf.keras.Sequential()

In [6]:
model.add(layers.SimpleRNN(1, return_sequences=True))
model.add(layers.SimpleRNN(1, return_sequences=False)) # 2, 1을 입력값을 받을 수 없다.

In [7]:
model(inputs)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.9871455],
       [-0.9694009]], dtype=float32)>

In [8]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (2, 5, 1)                 6         
                                                                 
 simple_rnn_1 (SimpleRNN)    (2, 1)                    3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


## Bi-directional RNN

![bidirectional_rnn](https://user-images.githubusercontent.com/11681225/46912324-3d53e400-cfad-11e8-8b09-85d8ebdb0e66.png)

In [9]:
model = tf.keras.Sequential()

In [10]:
model.add(layers.Bidirectional(layers.LSTM(1, return_sequences=True)))
model.add(layers.Bidirectional(layers.LSTM(1, return_sequences=True)))
model.add(layers.Bidirectional(layers.LSTM(1)))

In [11]:
model(inputs)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.06866948,  0.0715776 ],
       [-0.14023781,  0.09994718]], dtype=float32)>

In [12]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 bidirectional (Bidirection  (2, 5, 2)                 48        
 al)                                                             
                                                                 
 bidirectional_1 (Bidirecti  (2, 5, 2)                 32        
 onal)                                                           
                                                                 
 bidirectional_2 (Bidirecti  (2, 2)                    32        
 onal)                                                           
                                                                 
Total params: 112 (448.00 Byte)
Trainable params: 112 (448.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
